INSERT INTO `estado` VALUES (01,  'Acre');
INSERT INTO `estado` VALUES (02,  'Alagoas');
INSERT INTO `estado` VALUES (03,  'Amazonas');
INSERT INTO `estado` VALUES (04,  'Amapá');
INSERT INTO `estado` VALUES (05,  'Bahia');
INSERT INTO `estado` VALUES (06,  'Ceará');
INSERT INTO `estado` VALUES (07,  'Distrito Federal');
INSERT INTO `estado` VALUES (08,  'Espírito Santo');
INSERT INTO `estado` VALUES (09,  'Goiás');
INSERT INTO `estado` VALUES (10,  'Maranhão');
INSERT INTO `estado` VALUES (11,  'Minas Gerais');
INSERT INTO `estado` VALUES (12,  'Mato Grosso do Sul');
INSERT INTO `estado` VALUES (13,  'Mato Grosso');
INSERT INTO `estado` VALUES (14,  'Pará');
INSERT INTO `estado` VALUES (15,  'Paraíba');
INSERT INTO `estado` VALUES (16,  'Pernambuco');
INSERT INTO `estado` VALUES (17,  'Piauí');
INSERT INTO `estado` VALUES (18,  'Paraná');
INSERT INTO `estado` VALUES (19,  'Rio de Janeiro');
INSERT INTO `estado` VALUES (20,  'Rio Grande do Norte');
INSERT INTO `estado` VALUES (21,  'Rondônia');
INSERT INTO `estado` VALUES (22,  'Roraima');
INSERT INTO `estado` VALUES (23,  'Rio Grande do Sul');
INSERT INTO `estado` VALUES (24,  'Santa Catarina');
INSERT INTO `estado` VALUES (25,  'Sergipe');
INSERT INTO `estado` VALUES (26,  'São Paulo');
INSERT INTO `estado` VALUES (27,  'Tocantins');
